/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Formulario;

import Principal.Login;
import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ander
 */
public class PanelA extends javax.swing.JFrame {
ConexionBD con=new ConexionBD();
    Connection cn=con.conectar();
    
    DefaultTableModel Modelo_de_Tabla;
    Object[] OBJECTO = new Object[6];
    
      public void Imprimir_datos_en_la_tabla(){
          Modelo_de_Tabla =  (DefaultTableModel) Tabla.getModel();
          Modelo_de_Tabla.setRowCount(0);
        String qry1 = "SELECT * FROM usuarios";
        try {
        
        PreparedStatement datos=cn.prepareStatement(qry1);
        ResultSet rs = datos.executeQuery();
        
       while(rs.next()){

 OBJECTO[0]=rs.getString("Usuario");
 OBJECTO[1]=rs.getString("Nombre");
 OBJECTO[2]=rs.getString("Apellidos");
 OBJECTO[3]=rs.getString("Telefono");
 OBJECTO[4]=rs.getString("Email");
 OBJECTO[5]=rs.getString("Contraseña");
 Modelo_de_Tabla.addRow(OBJECTO);
 
    }
    

       
       
        
       
        
        }catch(Exception e){
            
        System.out.println(e);
               }
    }
        
    /** Creates new form panel_usuario_Administrador */
    public PanelA() {
        initComponents();
        Modelo_de_Tabla = (DefaultTableModel) Tabla.getModel();
        Imprimir_datos_en_la_tabla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Cerrarsesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UsuarioF = new javax.swing.JTextField();
        Editaruser = new javax.swing.JTextField();
        NombreF = new javax.swing.JTextField();
        Extraerinfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TelF1 = new javax.swing.JTextField();
        EliminarUSUARIO = new javax.swing.JButton();
        EmailF = new javax.swing.JTextField();
        ApellidoF = new javax.swing.JTextField();
        ContraseñaF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        setForeground(new java.awt.Color(0, 204, 204));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Apellido", "Teléfono", "Email", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));

        Cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Off.png"))); // NOI18N
        Cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarsesionActionPerformed(evt);
            }
        });

        jLabel1.setText("Cerrar sección");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setText("BASES DE DATOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Listado de todos los usuarios dentro del sistema, busque su usuario en base a los datos contenidos en los campos o agregue uno nuevo.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(331, 331, 331)
                .addComponent(Cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        UsuarioF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Usuario")), "Buscar usuario:"));
        UsuarioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioFActionPerformed(evt);
            }
        });

        Editaruser.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        Editaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditaruserActionPerformed(evt);
            }
        });

        NombreF.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        NombreF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFActionPerformed(evt);
            }
        });

        Extraerinfo.setText("Buscar");
        Extraerinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraerinfoActionPerformed(evt);
            }
        });

        jButton1.setText("Actualizar informacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TelF1.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono\n"));
        TelF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelF1ActionPerformed(evt);
            }
        });
        TelF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelF1KeyTyped(evt);
            }
        });

        EliminarUSUARIO.setText("Eliminar usuario");
        EliminarUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUSUARIOActionPerformed(evt);
            }
        });

        EmailF.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        EmailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFActionPerformed(evt);
            }
        });

        ApellidoF.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        ApellidoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoFActionPerformed(evt);
            }
        });

        ContraseñaF.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        ContraseñaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Editaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelF1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ApellidoF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(UsuarioF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(187, 187, 187)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Extraerinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(EliminarUSUARIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(UsuarioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Extraerinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Editaruser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ContraseñaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ApellidoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(EliminarUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(350, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarsesionActionPerformed
        // TODO add your handling code here:
        
     this.setVisible(false);
     new Login(null,true).setVisible(true);
    
    }//GEN-LAST:event_CerrarsesionActionPerformed

    private void UsuarioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioFActionPerformed

    private void NombreFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFActionPerformed

    private void ApellidoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoFActionPerformed

    private void ContraseñaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaFActionPerformed

    private void EmailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        List Camposincompletos = new ArrayList();
        
        String Usuario=UsuarioF.getText();
        String Nombre=NombreF.getText();
        String Apellidos=ApellidoF.getText();
        String Email=EmailF.getText();
        String Telefono=TelF1.getText();
        String Contraseña=ContraseñaF.getText();
        String Editarusuario=Editaruser.getText();
        
        
       
       boolean Cuser = Usuario.isEmpty()? false: true;
       boolean Cnombre = Nombre.isEmpty()? false: true;
       boolean CApeliido = Apellidos.isEmpty()? false: true;
       boolean Cemail = Email.isEmpty()? false: true;
       boolean CTelefono = Telefono.isEmpty()? false: true;
       boolean Ccontrasena = Contraseña.isEmpty()? false: true;
       boolean CEditarusuario = Editarusuario.isEmpty()? false: true;
       
       String Cincompleto="";
       
       //if(Cuser == false){Camposincompletos.add("Usuario" + "\n");};
       if(Cnombre == false){Camposincompletos.add("Nombre" +  "\n");};
       if(CApeliido == false){Camposincompletos.add("Apellido" + "\n");};
       if(Cemail == false){Camposincompletos.add("Email" + "\n");};
       if(CTelefono == false){Camposincompletos.add("Telefono" + "\n");};
       if(Ccontrasena == false){Camposincompletos.add("Contraseña" + "\n");};
       if(CEditarusuario == false){Camposincompletos.add("Usuario" + "\n");};
       
                    if(Camposincompletos.size()>0){
           
         for(int i=0;i<Camposincompletos.size();i++){
           
           
       Cincompleto+=Camposincompletos.get(i);
       
       }
         JOptionPane.showMessageDialog(null,("Favor completar: " + "\n" + Cincompleto ));
         
       
       }else{
                        
                 try{
                     
 String Qry= "UPDATE usuarios SET Nombre = ? ,Apellidos = ? , Usuario =  ? , Email = ? , Contraseña = ? , Confirmar =  ?, Telefono = ? WHERE usuario = ?";
   PreparedStatement Upd=cn.prepareStatement(Qry);  
   Upd.setString(1, Nombre);
   Upd.setString(2, Apellidos);
   Upd.setString(3, Editarusuario);
   Upd.setString(4, Email);
   Upd.setString(5, Contraseña);
   Upd.setString(6, Contraseña);
   Upd.setString(7, Telefono);
   Upd.setString(8, Usuario);
   Upd.executeUpdate();
   
        NombreF.setText("");
        ApellidoF.setText("");
        EmailF.setText("");
        ContraseñaF.setText("");
        TelF1.setText("");
        Editaruser.setText("");
        UsuarioF.setText("");
        

   Imprimir_datos_en_la_tabla();
   
   JOptionPane.showMessageDialog(null,"Los datos fueros actualizados");
   

                 }catch(Exception e){
                 System.out.println(e);
                 } 
                    
                    }
           
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TelF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelF1ActionPerformed

    private void ExtraerinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraerinfoActionPerformed
        // TODO add your handling code here:
        
    
    String Usuario=UsuarioF.getText();
    if(true == Usuario.isEmpty()){
        JOptionPane.showMessageDialog(null,"Campo no puede estar vacio");
    }else{
    
    
        
        
    try {
        
               PreparedStatement info=cn.prepareStatement("SELECT * FROM usuarios WHERE Usuario='"+Usuario+"'");
               ResultSet Uinfo=info.executeQuery();
               Uinfo.next();
               System.out.println(Uinfo.getRow());
               if(Uinfo.getRow()>0){
                   
        NombreF.setText(Uinfo.getString("Nombre"));
        ApellidoF.setText(Uinfo.getString("Apellidos"));
        EmailF.setText(Uinfo.getString("Email"));
        ContraseñaF.setText(Uinfo.getString("Contraseña"));
        TelF1.setText(Uinfo.getString("Telefono"));
        Editaruser.setText(Uinfo.getString("Usuario"));
        
        
               }else{
               
               JOptionPane.showMessageDialog(null,"Usuario no encontrado.");
               }
               
               
    }catch(Exception e){
    }
    }
    
    
    
        
        
        
    }//GEN-LAST:event_ExtraerinfoActionPerformed

    private void EliminarUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUSUARIOActionPerformed
        // TODO add your handling code here:
        String Usuario=UsuarioF.getText();
        String qry = "DELETE FROM usuarios WHERE Usuario = ? ";
        String qry1 = "SELECT * FROM usuarios WHERE Usuario = ? ";
    if(true == Usuario.isEmpty()){
        JOptionPane.showMessageDialog(null,"Campo no puede estar vacio");
    }else{
        
        try {
        
        PreparedStatement Cuser=cn.prepareStatement(qry1);
        Cuser.setString(1,UsuarioF.getText());
        ResultSet rs = Cuser.executeQuery();
        rs.next();
        
        if(rs.getRow()>0){
            
        PreparedStatement Eliusu=cn.prepareStatement(qry);
        Eliusu.setString(1,UsuarioF.getText());
        Eliusu.executeUpdate();
        JOptionPane.showMessageDialog(null,"Usuario eliminado.");
        Imprimir_datos_en_la_tabla();
        
        
            }else{
                    JOptionPane.showMessageDialog(null,"Usuario no encontrado.");}
        
    } catch (SQLException ex) {
        System.out.println(ex);
    }}

        
    }//GEN-LAST:event_EliminarUSUARIOActionPerformed

    private void TelF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelF1KeyTyped
        // TODO add your handling code here:
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
    
     if (!numeros)
    {
        evt.consume();
    }

    if (TelF1.getText().trim().length() == 10) {
        evt.consume();
    }
        
        
        
    }//GEN-LAST:event_TelF1KeyTyped

    private void EditaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditaruserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditaruserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoF;
    private javax.swing.JButton Cerrarsesion;
    private javax.swing.JTextField ContraseñaF;
    private javax.swing.JTextField Editaruser;
    private javax.swing.JButton EliminarUSUARIO;
    private javax.swing.JTextField EmailF;
    private javax.swing.JButton Extraerinfo;
    private javax.swing.JTextField NombreF;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField TelF1;
    private javax.swing.JTextField UsuarioF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
